local ADDON_NAME, namespace = ... 	--localization
local L = namespace.L 				--localization

--local LOCALE = GetLocale()

if namespace.locale == "zhTW" then
	-- The EU English game client also
	-- uses the US English locale code.

-- #######################################################################################################################
-- ##	繁體中文 (Traditional Chinese) translations provided by BNSSNB, killsophia, konraddo, and y123ao6 on Curseforge.	##
-- #######################################################################################################################

L["  /dcstats config: Opens the DejaClassicStats addon config menu."] = "/dcstats config: 開啟DejaClassicStats插件設置選項。"
L["  /dcstats reset:  Resets DejaClassicStats options to default."] = "/dcstats reset: 重置DejaClassicStats選項回預設。"
L["%s of %s increases %s by %.2f%%"] = "%s當%s 增加%s為%.2f%%"
L["About DCS"] = "關於DCS"
L["All Stats"] = "所有屬性"
L["Attack"] = "攻擊"
L["Average Durability"] = "平均耐久度"
L["Average equipped item durability percentage."] = "平均已裝備物品耐久度百分比。"
L["Average Item Level:"] = "平均物品等級："
L["Avoidance Rating"] = "迴避點數"
L["Blizzard's Hide At Zero"] = "以暴雪方式隱藏0值"
L["Character Stats:"] = "角色屬性："
L["Class Colors"] = "職業顏色"
L["Class Crest Background"] = "職業紋章背景"
L["Critical Strike Rating"] = "致命一擊點數"
L["DCS's Hide At Zero"] = "以DCS方式隱藏0值"
L["Decimals"] = "小數點"
L["Defense"] = "防禦"
L["Dejablue's improved character stats panel view."] = "Dejablue的角色屬性統計面板增強。"
L["DejaClassicStats Slash commands (/dcstats):"] = "DejaClassicStats指令(/dcstats)"
L["Displays a durability bar next to each item."] = "在每個物品的旁邊顯示耐久度條。"
L["Displays average item durability on the character shirt slot and durability frames."] = "在角色介面襯衫欄與耐久度框架顯示平均物品耐久度。"
L["Displays average item level to one decimal place."] = "顯示平均物品等級到小數點一位。"
L["Displays average item level to two decimal places."] = "顯示平均物品等級到小數點二位。"
L["Displays average item level with class colors."] = "以職業顏色顯示平均物品等級"
L["Displays each equipped item's durability."] = "顯示每個已裝備物品的耐久度。"
L["Displays each equipped item's repair cost."] = "顯示每個已裝備物品的修理費用。"
L["Displays 'Enhancements' category stats to two decimal places."] = "'強化'欄位的屬性顯示到兩個小數點。"
L["Displays Equipped/Available item levels unless equal."] = "顯示已裝備/可用的物品等級除非相等。"
L["Displays the class crest background."] = "顯示職業紋章背景。"
L["Displays the DCS scrollbar."] = "顯示DCS滾動條。"
L["Displays the Expand button for the character stats frame."] = "顯示打開角色屬性介面按鈕。"
L["Displays the item level of each equipped item."] = "顯示已裝備物品的等級"
L["Dodge Rating"] = "閃躲點數"
L["Durability"] = "耐久度"
L["Durability Bars"] = "耐久度條"
L["Equipped/Available"] = "已裝備/可用"
L["Expand"] = "打開"
L["General"] = "一般"
L["General global cooldown refresh time."] = "一般通用冷卻刷新時間。"
L["Global Cooldown"] = "通用冷卻"
L["Haste Rating"] = "加速點數"
L["Hide Character Stats"] = "隱藏角色屬性"
L["Hide low level mastery"] = "隱藏低等級精通"
L["Hides 'Enhancements' stats if their displayed value would be zero. Checking 'Decimals' changes the displayed value."] = [=[隱藏'強化'屬性如果顯示的值為零。
勾選'小數點'會改變顯示的數值。]=]
L["Hides 'Enhancements' stats only if their numerical value is exactly zero. For example, if stat value is 0.001%, then it would be displayed as 0%."] = [=[隱藏'強化'屬性只有當數值完全為零時。
舉例，如果屬性數值為0.001%，那麼它將顯示為0％。]=]
L["Hides Mastery stat until the character starts to have benefit from it. Hiding Mastery with Select-A-Stat™ in the character panel has priority over this setting."] = "隱藏精通屬性直到角色開始從中受益。使用角色視窗中Select-A-Stat™的精通隱藏會優先於此設置。"
L["Item Durability"] = "物品耐久度"
L["Item Level"] = "物品等級"
L["Item Repair Cost"] = "物品修理費用"
L["Item Slots:"] = "物品欄位："
L["Leech Rating"] = "汲取點數"
L["Lock DCS"] = "鎖定DCS"
L["Main Hand"] = "主手"
L["Mastery Rating"] = "精通點數"
L["Miscellaneous:"] = "雜項："
L["Movement Speed"] = "移動速度"
L["Off Hand"] = "副手"
L["Offense"] = "設置"
L["One Decimal Place"] = "小數點一位"
L["Parry Rating"] = "招架點數"
L["Ratings"] = "等級"
L["Relevant Stats"] = "相應屬性"
L["Repair Total"] = "總修理費用"
L["Requires Level "] = "需求等級"
L["Reset Stats"] = "重設屬性"
L["Reset to Default"] = "恢復為預設"
L["Resets order of stats."] = "重置屬性順序"
L["Scrollbar"] = "捲動條"
L["Show all stats."] = "顯示所有屬性"
L["Show Character Stats"] = "顯示角色屬性"
L["Show only stats relevant to your class spec."] = "只顯示你職業專精相關的屬性。"
L["Total equipped item repair cost before discounts."] = "已裝備物品未打折修理花費總計。"
L["Two Decimal Places"] = "兩位小數"
L["Unlock DCS"] = "解鎖DCS"
L["Versatility Rating"] = "臨機應變點數"
L["weapon auto attack (white) DPS."] = "武器自動攻擊(白字)每秒傷害。"
L["Weapon DPS"] = "武器每秒傷害"

----------------------------------------------------
-- DejaClassicStats specific translation phrases. --
----------------------------------------------------
L["Primary"] = "Primary"
L["Melee Enhancements"] = "Melee Enhancements"
L["Spell Enhancements"] = "Spell Enhancements"

L["\"Melee Hit: "] = "近戰命中:"
L[". Critical Hit immunity for a level 60 player against a raid boss occurs at 440 Defense and requires a defense skill of 140 from items and enhancements to achieve."] = "一個等級60的玩家對於團隊首領的致命一擊避免要有440防禦，需要從物品或是附魔增強讓防禦技能到140點。"
L["+Healing: "] = "+治療:"
L["Alternate Expand"] = "交替擴展"
L["Background Art"] = "背景美術"
L["Base Defense including talents such as Warrior's Anticipation is "] = "基礎的防禦包含天賦像是戰士的預感"
L["Black Item Icons"] = "黑色物品圖示"
L["Black item icons to make text more visible."] = "黑色物品圖示可讓文字更加明顯。"
L["Block: "] = "格檔:"
L["Bonus Defense from items and enhancements is "] = "來自物品與附魔增強的額外防禦"
L["Darken Item Icons"] = "深色物品圖示"
L["Darken item icons to make text more visible."] = "深色物品圖示可讓文字更加明顯。"
L["Defense: "] = "防禦:"
L["Display Info Beside Items"] = "在物品旁邊顯示訊息"
L["Displays black and white class talents background art."] = "顯示黑與白職業天賦背景美術。"
L["Displays each equipped item's enchantment."] = "顯示每個裝備物品的附魔。"
L["Displays the class talents background art."] = "顯示職業天賦背景美術。"
L["Displays the Expand button above the hands item slot."] = "在手部物品的上方顯示擴展按鈕。"
L["Displays the item's info beside each item's slot."] = "在每個物品部位旁邊顯示物品訊息。"
L["Dodge: "] = "閃避:"
L["Durability: "] = "耐久度:"
L["Enchants"] = "附魔"
L["Mana Regen Current: "] = "當前法力恢復:"
L["Mana Regen: "] = "法力恢復:"
L["Melee +Damage: "] = "近戰+傷害:"
L["Melee Crit: "] = "近戰致命一擊:"
L["Monochrome Background Art"] = "背景美術黑白化"
L["Movement Speed: "] = "移動速度:"
L["MP5: "] = "每5秒回魔:"
L["Parry: "] = "招架:"
L["Physical Critical Strike: "] = "物理致命一擊:"
L["Ranged Crit: "] = "遠程致命一擊:"
L["Repair Total: "] = "修理總計:"
L["Spell +Damage: "] = "法術+傷害:"
L["Spell Crit: "] = "法術致命一擊:"
L["Spell Hit: "] = "法術命中:"
L["Total Defense is "] = "總防禦為"

return end
