local _, addonTable = ...;

addonTable.Default = {
	["Ver"]={},
	["Error"] = {
		["ErrorDB"] = {},
		["ErrorTishi"] = false,
	},
	["Hardcore"] = {
		["CVars"]= {
			["Open"]=true,
			["NameMinV"]=0,
			["NameMaxV"]=16,
			["NameMinSelect"]=2,
			["NameMaxSelect"]=4,
		},
		["Deaths"]={
			["Open"]= true,
			["Tgminlevel"]= 20,
			["BigTgminlevel"]=50,
			["tipsmap"]=false,
			["UIScale"]= 1,
			["savedays"]= 1,
			["VoiceID"]= 3,
			["level"]= {},
			["List"]= {},
			["Player"]= {},
		},
	},
	["Common"] = {
		["QuestsEnd"]=true,
		["QuestsEndAudio"]=1,
		["SetFocus"]=false,
		["SetFocusMouse"]=true,
		["SetFocusKEY"]="shift",
		["ClearFocus"]=false,
		["ClearFocus_null"]=false,
		["Offnewfont"]=true,
		["addonProfilerEnabled"]=true,
		["AutoCombatLog"]= false,
		["AutoCombatLogTJ"]= 1,
	},
	["Interaction"] = {
		["AutoDown"] = true,
		["AutoDialogue"]=true,
		["AutoDialogueIndex"]=0,
		["AutoJierenwu"]=false,
		["AutoJiaorenwu"]=false,
		["AutoJyaoqing"]=false,
		["AutoFuhuo"]=false,
		["AutoRepair"] = true,
		["AutoRepair_GUILD"]=true,
		["RightPlus"] = true,
		["xiayijuli"]=0,
	},
	["Other"] = {
		["ErrorsHide"]=false,
		["PigLoad"]=false,
		["AFK"]={
			["Open"] = false,
			["QuickBut"]=true,
		},
	},
	["TradePlus"] = {
		["Open"] = true,
		["AddBut"] = true,
		["zhiyeLV"] = true,
	},
	["MailPlus"] = {
		["Open"] = true,
		["Coll"] = {},
		["MoneyEdit"] = true,
		["ALTbatch"] = true,
		["lianxuMode"] = true,
		["OpenAllCD"]=0.6,
	},
	["StatsInfo"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Qita_Num"] = true,
		["lixianBank"] = true,
		["TradeTongGao"]=false,
		["TradeTongGaoChannel"]="WHISPER",
		["TradeClassLV"]=true,
		["Players"] = {},
		["PlayerSH"] = {},
		["InstancesCD"] = {},
		["SkillData"] = {},
		["Times"] = {},
		["Token"] = {},
		["Items"] = {},
		["TradeData"] = {},
		["AHData"] = {},
	},
	["AutoSellBuy"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Diuqi_Tishi"]=false,
		["Diuqi_List"] = {},
		["Sell_Open"]=true,
		["Sell_But"]=true,
		["Sell_Tishi"]=true,
		["Sell_List"]={},
		["Sell_Lsit_Filtra"]={},
		["Buy_Open"]=true,
		["Buy_But"]=true,
		["Buy_Tishi"]=true,
		["Open_QkBut"] = false,
		["Open_Tishi"]=false,
		["Open_List"] = {},
		["Fen_QkBut"] = false,
		["Fen_Tishi"]=false,
		["Fen_List"] = {},
		["Xuan_QkBut"] = false,
		["Xuan_Tishi"]=false,
		["Xuan_List"] = {},
	},
	["AHPlus"]={
		["Open"] = true,
		["AHtooltip"] = true,
		["AHUIoff"]=true,
		["ScanTimeCD"]=4,
		["QuicAuc"]=false,
		["Coll"] = {},
		["CacheData"] = {},
		["DaojiTime"] = 0,
		["autoya"]=false,
		["yajingbiao"] = true,
		["exactMatch"] = false,
		["oldaucG"]=false,
		["SaveDuration"]=false,
		["SaveDuration_V"]=2,
	},
	["Chat"] = {
		["FastCopy"]=false,
		["WhoWhisper"]=true,
		["RemTips"]=true,
		["ShowLinkIcon"]=true,
		["ShowLinkLV"]=false,
		["ShowLinkSlots"]=false,
		["ShowLinkGem"]=false,
		["ShowZb"]=true,
		["LinkShow"]=false,
		["ClassColor"]=true,
		["Jianyin"] = false,
		["AltEX"] = false,
		["Guolv"] = false,
		["QuickChat"] = true,
		["QuickChat_style"]=1,
		["QuickChat_jianyin"]=false,
		["QuickChat_maodian"] = 1,
		["QuickChat_suofang"]=1,
		["QuickChat_pianyiX"]=0,
		["QuickChat_pianyiY"]=0,
		["QuickChat_ButHide"]={},
		["MinMaxB"] = false,
		["FontSize"] = false,
		["FontSize_value"] = 12,
		["JoinPindao"] = true,
		["jingjian"] = true,
		["TABqiehuanOpen"] = true,
		["TABqiehuanList"] = {},
		["chatZhanlian"] = {},
		["Tiqu"]={
			["Open"] = false,
			["Keys"]="",
			["jichengBlack"]=true,
			["AudioOpen"]=true,
			["Audio"]=1,
			["shuchumode"]=1,
			["ChatWox"]=0,
			["tiquOKFlash"]=true,
			["KeywordFHeight"]=140,
			["CombatHide"]=false,
		},
		["Filter"] = {
			["Open"]=true,
			["BlackName"]=true,
			["FilterRepeat"]=true,
			["IGNORE_DND"]=true,
			["FBneiNO"]=false,
			["FilterChannel"]={
				["CHANNEL"]=true,
				["YELL"]=true,
				["SAY"]=false,
				["WHISPER"]=false,
			},
			["Blacks"]="",
			["Blacks_P"]="",
			["Precise"]=false,
		},
		["Channel_List"]={},
	},
	["Chatjilu"] = {
		["Days"]=7,
		["WHISPER"]={
			["Open"]=true,
			["Tips"]=true,
			["record"]={},
			["jichengBlack"]=true,
		},
		["PARTY"]={
			["Open"]=true,
			["Tips"]=true,
			["record"]={},
		},
		["RAID"]={
			["Open"]=true,
			["Tips"]=true,
			["record"]={},
		},
		["GUILD"]={
			["Open"]=true,
			["Tips"]=true,
			["record"]={},
		},
		["INSTANCE_CHAT"]={
			["Open"]=true,
			["Tips"]=true,
			["record"]={},
		},
	},
	["ActionBar"] = {
		["Ranse"] = true,
		["ActionCD"] = true,
		["Cailiao"] = true,
		["PetTishi"] = true,
		["AutoFanye"] = false,
	},
	["QuickBut"]={
		["Open"] = true,
		["bili"]=1,
		["Lock"]=false,
		["BGbroadcast"]=true,
		["Lushi"]=true,
		["Spell"]=true,
		["SpellClose"]=true,
		["Rune"]=true,
		["RuneShow"]=false,
		["Equip"]=true,
		["Trinket"]=true,
		["TrinketFenli"]=false,
		["TrinketFenliPailie"]=1,
		["TrinketFenlilock"]=false,
		["TrinketScale"]=1,
	},
	["BagBank"]={
		["BagKongyu"]=true,
		["Zhenghe"] = true,
		["SortBagsRightToLeft"] = false,
		["JianjieMOD"] = false,
		["SortBag_Config"]=true,
		["wupinLV"]=true,
		["JunkShow"]=true,
		["BAGmeihangshu"]=8,
		["BAGsuofangBili"]=1,
		["BANKmeihangshu"]=16,
		["BANKmeihangshu_retail"]=17,
		["BANKsuofangBili"]=1,
		["jiaoyiOpen"]=true,
		["AHOpen"]=true,
		["wupinRanse"]=true,
		["NewItem"]=true,
	},
	["FramePlus"] = {
		["AddonList"]=true,
		["AddonStatus"]={},
		["UIWidget"] = true,
		["UIWidgetPointX"]=0;
		["UIWidgetPointY"]=-30;
		["Roll"] = true,
		["RollScale"] = 1,
		["Loot"] = true,
		["LootMasterErr"]=true,
		["Macro"] = true,
		["Friends"] = true,
		["Merchant"] = true,
		["BuffTime"] = true,
		["Talent"] = true,
		["Skill"] = true,
		["Skill_QKbut"]=true,
		["Quest"] = true,
		["Tracking"] = true,
		["Character_Durability"] = true,
		["Character_ItemLevel"]=true,
		["Character_ItemColor"]=true,
		["Character_ItemList"]=true,
		["Character_Shuxing"] = true,
		["BlizzardUI_Move"] = true,
		["BlizzardUI_Move_Save"]=true,
	},
	["Tooltip"] = {
		["ItemSell"] = true,
		["ItemLevel"] = true,
		["ItemMaxCount"] = true,
		["IDinfo"] = true,
		["PointOpen"]=false,
		["Point"] = 1,
		["PointX"] = 0,
		["PointY"] = 0,
	},
	["UnitFrame"] = {
		["PlayerFrame"] = {
			["HPFF"] = true,	
		},
		["TargetFrame"] = {
			["Plus"] = true,
			["Chouhen"] = true,
			["ToToToT"] = true,
			["Yisu"] = true,
			["BigDebuff"] = false,
		},
		["PartyMemberFrame"] = {
			["Plus"] = true,
			["HPFF"] = true,
			["Buff"] = true,
			["ToToT"] = true,
		},
	},
	["CombatPlus"] = {
		["PetHappiness"]=true,
		["ammotips"]=true,
		["Submerged"]=true,
		["markerR"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["AutoShow"] = true,
			["NoGroup"]=false,
			["NoTarget"]=true,
		},
		["markerW"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["AutoShow"] = true,
		},
		["HPMPBar"]={
			["Open"] = true,
			["Showshuzhi"]=true,
			["CombatShow"]=true,
			["FontSize"]=10,
			["Xpianyi"]=0,
			["Ypianyi"]=-80,
			["BarTex"]=1,
			["BarW"]=150,
			["BarH"]=12,
			["HpShow"]=true,
			["MpShow"]=true,
			["Fuziyuan"]=true,
			["FuStyle"]={},
		},
		["AttackBar"]={
			["Open"] = false,
			["Showshuzhi"]=true,
			["Scale"]=1,
			["Xpianyi"]=0,
			["Ypianyi"]=14,
		},
	},
	["Map"] = {
		["MinimapBpaichu"] = {},
		["MinimapPos"] = -13.62698465698976,
		["MinimapPointMode"] = 1,
		["MinimapBut"] = true,
		["MiniButShouNa_YN"] = 1,
		["MiniButShouNa_hang"] = 5,
		["MinimapPointXY"] = {0, 0},
		["MinimapPoint_NDui"] = {0, 0},
		["MinimapPoint_ElvUI"] = {28, 0},
		["WorldMapBili"] = 0.8,
		["WorldMapPlus"] = false,
		["WorldMapWind"] = true,
		["WorldMapXY"] = true,
		["WorldMapLV"] = true,
		["WorldMapSkill"] = true,
		["WorldMapMiwu"] = true,
		["WorldMapFuben"] = true,
		["WorldMapNPC"] = true,
	},
	["CVars"]={
		["MaxZoom"]= true,
		["EaseUse"]=true,
		["Fast_Loot"]=false,
		["Shaman_Blue"]=true,
	},
	["PigLayout"]={
		["TopBar"]={
			["Open"] = false,
			["AnchorPoint"]="TOP",
			["Height"]=22,
			["Backdrop"]=1,
			["Alpha"]=1,
		},
		["MicroMenu"]={
			["Open"] = false,
			["Scale"]=1,
			["Interval"]=0,
			["AnchorPoint"]="TOP",
			["AnchorPointX"]=0,
			["AnchorPointY"]=0,
			["HideBut"]={},
		},
		["ActionBar"] = {
			["HideShijiu"] = false,
			["Scale"]=false,
			["ScaleV"]=0.8,
			["BarRight"] = false,
			["Layout"] = 1,
			["LRInterval"]=20,
		},
		["ChatUI"] = {
			["editMove"] = false,
			["editPoint"] = {0,0},
			["Margin"] = false,
			["MarginPoint"] = {35,35,0,0},
			["Zhu"] = false,
			["ZhuPoint"] = {370,200,35,35},
			["Fu"] = false,
			["FuPoint"] = {370,200,35,35},
		},
		["topMenu"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["HideBut"]={},
			["TimerMode"]=1,
			["daojishiTime"]=10,
			["Countdown"]=false,
			["CountdownAudio"]=1,
			["CountdownEnd"]=false,
			["CountdownEndAudio"]=1,
		},
		["topInfoL"] = {
			["Open"] = false,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["HideBut"]={},
		},
		["topInfoR"] = {
			["Open"] = false,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["HideBut"]={},
		},
	},
	["Pig_UI"] = {},
	["Blizzard_UI"] = {},
};
addonTable.Default_Per = {
	["Pig_UI"] = {},
	["CombatPlus"] = {
		["PetFoodList"]={},
	},
	["AutoSellBuy"] = {
		["Buy_List"]={},
		["Save_List"] = {},
		["Save_Money"] = 10000000,
		["Take_List"] = {},
		["Take_Money"] = 10000000,
	},
	["PigAction"] = {
		["Open"] = {false,false,false,false},
		["Lock"] = {false,false,false,false},
		["Scale"] = {1,1,1,1},
		["Pailie"] = {1,1,1,1},
		["AnniuNum"] = {12,12,12,12},
		["ShowTJ"] = {1,1,1,1},
		["ActionData"] = {},
	},
	["QuickBut"]={
		["ActionData"] = {},
		["EquipList"]={},
		["TrinketMode"]=1,
		["TrinketList"]={},
		["LushiID"]=6948,
	},
};