local _, addonTable = ...;

addonTable.Default = {
	["Ver"]={},
	["PigUIPoint"] = {},
	["WowUI"] = {},
	["Error"] = {
		["ErrorDB"] = {},
		["ErrorTishi"] = false,
	},
	["Common"] = {
		["QuestsEnd"]=true,
		["QuestsEndAudio"]=1,
		["SetFocus"]=false,
		["SetFocusMouse"]=true,
		["SetFocusKEY"]="shift",
		["ClearFocus"]=false,
		["ClearFocus_null"]=false,
		["Offnewfont"]=true,
		["AutoCVars"]=true,
		["AutoLoot"] = true,
		["FastLoot"]=true,
		["SHAMAN_Color"]=true,
		["AutoCombatLog"]= false,
		["AutoCombatLogTJ"]= 1,
	},
	["Interaction"] = {
		["AutoDown"] = true,
		["AutoDialogue"]=true,
		["AutoJierenwu"]=false,
		["AutoJiaorenwu"]=false,
		["AutoJyaoqing"]=false,
		["AutoFuhuo"]=false,
		["AutoRepair"] = true,
		["AutoRepair_GUILD"]=true,
		["RightPlus"] = true,
		["xiayijuli"]=0,
	},
	["QuickFollow"] = {
		["QuickBut"] = false,
		["Name"] = "猪猪加油",
		["Kaishi"] = "1",
		["Jieshu"] = "2",
		["Duizhang"] = true,
		["Tishi"] = false,
		["Qiangli"]=false,
		["Jiuwei"] = false,
		["Yijiao"]=false,
	},
	["Other"] = {
		["ErrorsHide"]=false,
		["PigLoad"]=false,
		["AFK"]={
			["Open"] = false,
			["QuickBut"]=true,
			["TispTXT"]="临时离开，勿动!!!",
		},
	},
	["TradePlus"] = {
		["Open"] = true,
		["AddBut"] = true,
		["zhiyeLV"] = true,
	},
	["MailPlus"] = {
		["Open"] = true,
		["Coll"] = {},
		["MoneyEdit"] = true,
		["ALTbatch"] = true,
		["lianxuMode"] = true,
		["OpenAllCD"]=0.6,
	},
	["StatsInfo"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Qita_Num"] = true,
		["lixianBank"] = true,
		["Players"] = {},
		["PlayerSH"] = {},
		["SkillCD"] = {},
		["FubenCD"] = {},
		["Token"] = {},
		["Items"] = {},
		["AHData"] = {},
		["TradeTongGao"]=false,
		["TradeTongGaoChannel"]="WHISPER",
		["TradeClassLV"]=true,
		["TradeData"] = {},
	},
	["AutoSellBuy"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Diuqi_Tishi"]=false,
		["Diuqi_List"] = {},
		["Sell_Open"]=true,
		["Sell_But"]=true,
		["Sell_Tishi"]=true,
		["Sell_List"]={},
		["Sell_Lsit_Filtra"]={},
		["Buy_Open"]=true,
		["Buy_But"]=true,
		["Buy_Tishi"]=true,
		["Open_QkBut"] = false,
		["Open_Tishi"]=false,
		["Open_List"] = {},
		["Fen_QkBut"] = false,
		["Fen_Tishi"]=false,
		["Fen_List"] = {},
		["Xuan_QkBut"] = false,
		["Xuan_Tishi"]=false,
		["Xuan_List"] = {},
	},
	["AHPlus"]={
		["Open"] = true,
		["AHtooltip"] = true,
		["AHUIoff"]=true,
		["ScanCD_M"]=0.0002,
		["ScanCD"]=0.004,
		["QuicAuc"]=false,
		["Time"] = 48,
		["Tokens"] = {},
		["Coll"] = {},
		["DataList"] = {},
		["DaojiTime"] = 0,
		["autoya"]=false,
		["yajingbiao"] = true,
		["exactMatch"] = false,
		["oldaucG"]=false,
	},
	["Chat"] = {
		["FastCopy"]=false,
		["WhoWhisper"]=true,
		["RemTips"]=true,
		["ChatSetSave"]={},
		["ShowLinkIcon"]=true,
		["ShowZb"]=true,
		["LinkShow"]=false,
		["ClassColor"]=true,
		["Jianyin"] = false,
		["AltEX"] = false,
		["Guolv"] = false,
		["QuickChat"] = true,
		["QuickChat_style"]=1,
		["QuickChat_jianyin"]=false,
		["QuickChat_maodian"] = 1,
		["QuickChat_suofang"]=1,
		["QuickChat_pianyiX"]=0,
		["QuickChat_pianyiY"]=0,
		["QuickChat_ButList"]={},
		["MinMaxB"] = false,
		["FontSize"] = false,
		["FontSize_value"] = 12,
		["JoinPindao"] = true,
		["jingjian"] = true,
		["TABqiehuanOpen"] = true,
		["TABqiehuanList"] = {},
		["chatZhanlian"] = {},
		["Tiqu"]={
			["Open"] = false,
			["Keys"]="",
			["jichengBlack"]=true,
			["Audio"]=1,
			["shuchumode"]=1,
			["ChatWox"]=0,
			["tiquOKFlash"]=true,
			["KeywordFShow"]=true,
			["BgColor"]={0,0,0,0.4},
			["KeywordFHeight"]=140,
			["CombatHide"]=false,
		},
		["Filter"] = {
			["Open"]=true,
			["BlackName"]=true,
			["FilterRepeat"]=true,
			["IGNORE_DND"]=true,
			["FBneiNO"]=false,
			["FilterChannel"]={
				["CHANNEL"]=true,
				["YELL"]=true,
				["SAY"]=false,
				["WHISPER"]=false,
			},
			["Blacks"]="",
			["Blacks_P"]="",
			["Precise"]=false,
		},
		["Channel_List"]={},
		["Frame"] = {
			["Bianju"] = true,
			["editMove"] = false,
			["editPoint_X"] = 0,
			["editPoint_Y"] = 0,
			["Width"] = false,
			["Width_value"] = 350,
			["Height"] = false,
			["Height_value"] = 180,
			["Point"] = false,
			["Point_X"] = 35,
			["Point_Y"] = 80,
			["Loot_Width"] = false,
			["Loot_Width_value"] = 350,
			["Loot_Height"] = false,
			["Loot_Height_value"] = 180,
			["Loot_Point"] = false,
			["Loot_Point_X"] = 26,
			["Loot_Point_Y"] = 8,
			["ShowChannel"] = true,
		},
	},
	["Chatjilu"] = {
		["tianshu"]=7,
		["jiluinfo"]={},
	},
	["ActionBar"] = {
		["Ranse"] = true,
		["ActionCD"] = true,
		["Cailiao"] = true,
		["PetTishi"] = true,
		["AutoFanye"] = false,
		["HideShijiu"] = false,
		["BarRight"] = false,
		["ActionBar_bili"]=false,
		["ActionBar_bili_value"]=1,
		-- ["MenuBag"] = false,
		-- ["MenuBag_bili_value"]=0.9;
	},
	["QuickBut"]={
		["Open"] = true,
		["bili"]=1,
		["Lock"]=false,
		["BGbroadcast"]=true,
		["Lushi"]=true,
		["Spell"]=true,
		["Rune"]=true,
		["RuneShow"]=false,
		["Equip"]=true,
		["Trinket"]=true,
		["TrinketFenli"]=false,
		["TrinketFenliPailie"]=1,
		["TrinketFenlilock"]=false,
		["TrinketScale"]=1,
	},
	["BagBank"]={
		["BagKongyu"]=true,
		["Zhenghe"] = true,
		["SortBagsRightToLeft"] = false,
		["JianjieMOD"] = false,
		["hulueBAG"] = {false,false,false,false,false},
		["hulueBANK"] = {false,false,false,false,false,false,false,false},
		["lixian"] = {},
		["SortBag_Config"]=true,
		["wupinLV"]=true,
		["JunkShow"]=true,
		["BAGmeihangshu"]=8,
		["BAGmeihangshu_WLK"]=10,
		["BAGmeihangshu_retail"]=10,
		["BAGsuofangBili"]=1,
		["BANKmeihangshu"]=16,
		["BANKmeihangshu_retail"]=17,
		["BANKsuofangBili"]=1,
		["jiaoyiOpen"]=true,
		["AHOpen"]=true,
		["wupinRanse"]=true,
	},
	["FramePlus"] = {
		["AddonList"]=true,
		["Roll"] = true,
		["RollScale"] = 1,
		["Loot"] = true,
		["Macro"] = true,
		["Friends"] = true,
		["Merchant"] = true,
		["BuffTime"] = true,
		["Talent"] = true,
		["Skill"] = true,
		["Skill_QKbut"]=true,
		["Quest"] = true,
		["Zhuizong"] = true,
		["Character_naijiu"] = true,
		["Character_ItemLevel"]=true,
		["Character_ItemColor"]=true,
		["Character_ItemList"]=true,
		["Character_Shuxing"] = true,
		["BlizzardUI_Move"] = true,
		["BlizzardUI_Move_Save"]=true,
	},
	["Tooltip"] = {
		["ItemSell"] = true,
		["ItemLevel"] = true,
		["ItemMaxCount"] = true,
		["IDinfo"] = true,
		["PointOpen"]=false,
		["Point"] = 1,
		["PointX"] = 0,
		["PointY"] = 0,
	},
	["UnitFrame"] = {
		["PlayerFrame"] = {
			["Plus"] = true,
			["Loot"] = true,
			["HPFF"] = true,	
		},
		["TargetFrame"] = {
			["Plus"] = true,
			["Chouhen"] = true,
			["ToToToT"] = true,
			["Yisu"] = true,
			["BigDebuff"] = false,
		},
		["PartyMemberFrame"] = {
			["Plus"] = true,
			["HPFF"] = true,
			["Buff"] = true,
			["ToToT"] = true,
		},
	},
	["CombatPlus"] = {
		["markerR"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["AutoShow"] = true,
			["NoGroup"]=false,
			["NoTarget"]=true,
		},
		["markerW"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["AutoShow"] = true,
		},
		["topMenu"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = false,
			["Scale"]=1,
			["daojishiFun"]=1,
			["daojishiTime"]=5,
		},
		["CombatTime"]={
			["Open"] = true,
			["Lock"] = false,
			["Miaobian"]="OUTLINE",
			["Beijing"]=1,
			["Scale"]=1,
		},
		["HPMPBar"]={
			["Open"] = true,
			["Showshuzhi"]=true,
			["Fuziyuan"]=true,
			["CombatShow"]=true,
			["Scale"]=1,
			["Xpianyi"]=0,
			["Ypianyi"]=-80,
		},
		["AttackBar"]={
			["Open"] = false,
			["Showshuzhi"]=false,
			["Scale"]=1,
			["Xpianyi"]=0,
			["Ypianyi"]=14,
		},
	},
	["Map"] = {
		["MinimapBpaichu"] = {},
		["MinimapPos"] = -13.62698465698976,
		["MinimapPoint"] = 1,
		["MinimapBut"] = true,
		["MiniButShouNa_YN"] = 1,
		["MiniButShouNa_hang"] = 5,
		["WorldMapBili"] = 0.8,
		["WorldMapPlus"] = false,
		["WorldMapWind"] = true,
		["WorldMapXY"] = true,
		["WorldMapLV"] = true,
		["WorldMapSkill"] = true,
		["WorldMapMiwu"] = true,
		["WorldMapFuben"] = true,
		["WorldMapNPC"] = true,
	},
	["CVars"]={
		["MaxZoom"]= true,
	},
};
addonTable.Default_Per = {
	["AutoSellBuy"] = {
		["Buy_List"]={},
		["Save_List"] = {},
		["Save_Money"] = 10000000,
		["Take_List"] = {},
		["Take_Money"] = 10000000,
	},
	["QuickFollow"]={
		["beidongOpen"]=false,
	},
	["PigAction"] = {
		["Open"] = {false,false,false,false},
		["Lock"] = {false,false,false,false},
		["Scale"] = {1,1,1,1},
		["Pailie"] = {1,1,1,1},
		["AnniuNum"] = {12,12,12,12},
		["ShowTJ"] = {1,1,1,1},
		["ActionData"] = {},
	},
	["QuickBut"]={
		["ActionData"] = {},
		["EquipList"]={},
		["TrinketMode"]=1,
		["TrinketList"]={},
		["LushiID"]=6948,
	},
};