local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "deDE")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Zauberbalken automatisch positionieren"
L["BORDER_COLOR"] = "Randfarbe auswählen"
L["CAST_BORDER"] = "Randtextur auswählen"
L["CAST_FONT"] = "Schriftart des Zauberbalken auswählen"
L["CAST_STATUSBAR"] = "Zauberbalken-Textur auswählen"
L["CASTBAR"] = "Zauberbalken"
L["CASTBAR_COLORS"] = "Zauberbalken-Farben"
L["CASTBAR_ICON"] = "Zauberbalken-Symbol"
L["CASTBAR_SIZING"] = "Zauberbalken-Größe"
L["CASTBAR_TEXTURE_FONT"] = "Zauberbalken-Texturen"
L["DEFAULT"] = "Standard"
L["FONT_SIZE"] = "Schriftgröße"
L["GENERAL"] = "Allgemeine Einstellungen"
L["HEIGHT"] = "Höhe des Zauberbalken"
L["ICON_HIDE_BORDER"] = "Symbolrand verstecken"
L["ICON_POS_X"] = "Symbol-Position X"
L["ICON_POS_Y"] = "Symbol-Position Y"
L["ICON_SHOW"] = "Zaubersymbol anzeigen"
L["ICON_SIZE"] = "Symbolgröße"
L["NAMEPLATE"] = "Namensplakette"
L["PARTY"] = "Gruppe"
L["PLAYER"] = "Spieler"
L["RESET_ALL"] = "Einstellungen zurücksetzen"
L["SHOW_CAST_INFO_ONLY"] = "Nur Zauber-Info anzeigen"
L["SHOW_TIMER"] = "Zeitanzeige anzeigen"
L["STATUS_BG_COLOR"] = "Hintergrundfarbe auswählen"
L["STATUS_CHANNEL_COLOR"] = "Kanalisierungsfüllfarbe auswählen"
L["STATUS_COLOR"] = "Zauberfüllfarbe auswählen"
L["TARGET"] = "Ziel"
L["TEST"] = "Testmodus für"
L["TEST_MODE_DRAG"] = "Testmodus - ziehen zum bewegen"
L["TEXT_COLOR"] = "Textfarbe auswählen"
L["TEXT_POS_X"] = "Text-Position X"
L["TEXT_POS_Y"] = "Text-Position Y"
L["TOGGLE_CASTBAR"] = "Zauberbalken aktivieren"
L["WIDTH"] = "Breite des Zauberbalken"

