local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "frFR")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Position automatique de Castbar"
L["AUTO_POS_BAR_TOOLTIP"] = "Lorsqu'il est activé, la barre de Cast sera automatiquement positionnée en fonction de facteurs tels que les buffs sont montrés sur le cadre de l’unité, etc. Ne fonctionne pas avec les cadres d'unité tiers."
L["BORDER_COLOR"] = "Sélectionnez la couleur de la bordure"
L["CAST_BORDER"] = "Sélectionner une texture de bordure"
L["CAST_BORDER_TOOLTIP"] = "Sélectionnez la texture pour la bordure de Castbar"
L["CAST_FONT"] = "Sélectionner la police de Castbar"
L["CAST_FONT_TOOLTIP"] = "Sélectionnez le type de police utilisé pour le nom et le texte du minuteur."
L["CAST_STATUSBAR"] = "Sélectionnez Texture Castbar"
L["CAST_STATUSBAR_TOOLTIP"] = "Sélectionnez le type de texture utilisé pour la barre de cast / barre de statut."

