local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "ptBR")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Posicionar automaticamente a barra de lançamento"
L["AUTO_POS_BAR_TOOLTIP"] = "Quando ativado, ele posicionará automaticamente a barra de lançamento com base em coisas como quantos buffs são mostrados no quadro da unidade e assim por diante. Não funciona com quadros de unidades de terceiros."
L["BORDER_COLOR"] = "Selecionar cor da borda"
L["CAST_BORDER"] = "Selecionar textura da borda"
L["CAST_FONT"] = "Selecionar fonte da barra de lançamento"
L["CAST_FONT_TOOLTIP"] = "Selecione o tipo de fonte usado para o nome do feitiço e o texto do cronômetro."
L["CASTBAR"] = "Barra de lançamento"
L["CASTBAR_COLORS"] = "Cores da barra de lançamento"
L["FONT_SIZE"] = "Tamanho da fonte"
L["FRAME_LEVEL"] = "Nível de quadro"
L["GENERAL"] = "Configurações Gerais"
L["HEIGHT"] = "Altura da barra de lançamento"
L["HEIGHT_TOOLTIP"] = "Define a altura da barra de lançamento"
L["ICON_HIDE_BORDER"] = "Ocultar borda do ícone"
L["ICON_POS_X"] = "Posição do ícone X"
L["ICON_POS_Y"] = "Posição do ícone Y"
L["ICON_SHOW"] = "Mostrar ícone de feitiço"
L["ICON_SIZE"] = "Tamanho do ícone"
L["LSM_TEXTURE_NOTE"] = "Nota: Se você usar uma textura/fonte personalizada de terceiros e excluí-la mais tarde do seu PC, precisará redefinir manualmente a textura ou fonte aqui para que o complemento continue funcionando."
L["NAMEPLATE"] = "Placa de identificação"
L["PARTY"] = "Grupo"
L["PLAYER"] = "Jogador"
L["POSXY_TOOLTIP"] = "Ajuste os valores de deslocamento XY para mover o quadro."
L["RESET_ALL"] = "Redefinir todas as configurações"
L["SHOW_TIMER"] = "Mostrar texto do temporizador"
L["STATUS_BG_COLOR"] = "Selecionar cor de fundo"
L["STATUS_CHANNEL_COLOR"] = "Selecionar cor de preenchimento do canal"
L["TEST_MODE_DRAG"] = "Modo de teste - Arraste para mover"
L["TEXT_COLOR"] = "Selecionar cor do texto"
L["TEXT_POS_X"] = "Posição do texto X"
L["TEXT_POS_Y"] = "Posição do texto Y"
L["WIDTH"] = "Largura da barra de lançamento"
L["WIDTH_TOOLTIP"] = "Define a largura da barra de lançamento"

