-- English

-- MonkeySpeed config variables descritions
MONKEYSPEED_GENERAL_OPTIONS				= "General Options:"
MONKEYSPEED_shown_DESC					= "Enable MonkeySpeed"
MONKEYSPEED_frameColour_DESC			= "Frame Color"
MONKEYSPEED_showBorder_DESC				= "Display the border"
MONKEYSPEED_borderColour_DESC			= "Border Color"
MONKEYSPEED_frameLocked_DESC			= "Lock the frame position"
MONKEYSPEED_showBar_DESC				= "Display color bar"
MONKEYSPEED_showLDB_DESC				= "Update LDB plugin"
MONKEYSPEED_showLDB_inactive			= "inactive"
MONKEYSPEED_showPercent_DESC			= "Display percent text"
MONKEYSPEED_autoCalibration_DESC		= "Simulate Unit Pitch"
MONKEYSPEED_maximumSpeed_DESC			= "Display maximum speed"
MONKEYSPEED_MISC_OPTIONS				= "Miscellaneous Options:"
MONKEYSPEED_leftClickToggles_DESC		= "Left mouse click toggles MonkeySpeed frame"
MONKEYSPEED_shiftLeftClickLocks_DESC	= "Shift+left mouse click locks/unlocks the frame"
MONKEYSPEED_rightClickOpensConfig_DESC	= "Right mouse click opens the config frame"
MONKEYSPEED_speedColour1_DESC			= "Speed at 0%"
MONKEYSPEED_speedColour2_DESC			= "Speed at >0% and <100%"
MONKEYSPEED_speedColour3_DESC			= "Speed at 100%"
MONKEYSPEED_speedColour4_DESC			= "Speed at >100% and <200%"
MONKEYSPEED_speedColour5_DESC			= "Speed at 200%"
MONKEYSPEED_speedColour6_DESC			= "Speed at >200% and <380%"
MONKEYSPEED_speedColour7_DESC			= "Speed at 380%"
MONKEYSPEED_speedColour8_DESC			= "Speed at >380% and <410%"
MONKEYSPEED_speedColour9_DESC			= "Speed at 410%"
MONKEYSPEED_speedColour10_DESC			= "Speed at >410% to infinity"
MONKEYSPEED_precision_DESC				= "Decimal points"