-- English

-- MonkeySpeed config variables descritions
MONKEYSPEED_GENERAL_OPTIONS				= "General Options:"
MONKEYSPEED_shown_DESC					= "Enable MonkeySpeed"
MONKEYSPEED_frameColour_DESC			= "Frame Color"
MONKEYSPEED_showBorder_DESC				= "Display the border"
MONKEYSPEED_borderColour_DESC			= "Border Color"
MONKEYSPEED_frameLocked_DESC			= "Lock the frame position"
MONKEYSPEED_showBar_DESC				= "Display color bar"
MONKEYSPEED_showLDB_DESC				= "Update LDB plugin"
MONKEYSPEED_showLDB_inactive			= "inactive"
MONKEYSPEED_showPercent_DESC			= "Display percent text"
MONKEYSPEED_autoCalibration_DESC		= "Simulate Unit Pitch"
MONKEYSPEED_maximumSpeed_DESC			= "Display maximum speed"
MONKEYSPEED_MISC_OPTIONS				= "Miscellaneous Options:"
MONKEYSPEED_leftClickToggles_DESC		= "Left mouse click toggles MonkeySpeed frame"
MONKEYSPEED_shiftLeftClickLocks_DESC	= "Shift+left mouse click locks/unlocks the frame"
MONKEYSPEED_rightClickOpensConfig_DESC	= "Right mouse click opens the config frame"
MONKEYSPEED_speedColour1_DESC			= "Speed at 0%"
MONKEYSPEED_speedColour2_DESC			= "Speed at >0% and <100%"
MONKEYSPEED_speedColour3_DESC			= "Speed at 100%"
MONKEYSPEED_speedColour4_DESC			= "Speed at >100% and <200%"
MONKEYSPEED_speedColour5_DESC			= "Speed at 200%"
MONKEYSPEED_speedColour6_DESC			= "Speed at >200% and <380%"
MONKEYSPEED_speedColour7_DESC			= "Speed at 380%"
MONKEYSPEED_speedColour8_DESC			= "Speed at >380% and <410%"
MONKEYSPEED_speedColour9_DESC			= "Speed at 410%"
MONKEYSPEED_speedColour10_DESC			= "Speed at >410% to infinity"
MONKEYSPEED_precision_DESC				= "Decimal points"

if (GetLocale() == "zhTW") then

-- MonkeySpeed config variables descritions
MONKEYSPEED_GENERAL_OPTIONS				= "一般選項"
MONKEYSPEED_shown_DESC					= "啟用MonkeySpeed"
MONKEYSPEED_frameColour_DESC			= "視窗底色"
MONKEYSPEED_showBorder_DESC				= "顯示邊框"
MONKEYSPEED_borderColour_DESC			= "邊框顏色"
MONKEYSPEED_frameLocked_DESC			= "鎖定位置"
MONKEYSPEED_showBar_DESC				= "隨移動速度變色"
MONKEYSPEED_showLDB_DESC				= "訊息條"
MONKEYSPEED_showLDB_inactive			= "開發中"
MONKEYSPEED_showPercent_DESC			= "顯示百分比"
MONKEYSPEED_autoCalibration_DESC		= "估算游泳和飛行時的單位速度"
MONKEYSPEED_maximumSpeed_DESC			= "顯示最快速度"
MONKEYSPEED_MISC_OPTIONS				= "細節選項："
MONKEYSPEED_leftClickToggles_DESC		= "左鍵點擊視窗拖動"
MONKEYSPEED_shiftLeftClickLocks_DESC	= "Shift+右鍵點擊視窗解鎖移動"
MONKEYSPEED_rightClickOpensConfig_DESC	= "右鍵點擊視窗開啟設定選項"
MONKEYSPEED_speedColour1_DESC			= "0%"
MONKEYSPEED_speedColour2_DESC			= "0%到100%之間"
MONKEYSPEED_speedColour3_DESC			= "100%"
MONKEYSPEED_speedColour4_DESC			= "100%到200%"
MONKEYSPEED_speedColour5_DESC			= "200%"
MONKEYSPEED_speedColour6_DESC			= "200%到380%之間"
MONKEYSPEED_speedColour7_DESC			= "380%"
MONKEYSPEED_speedColour8_DESC			= "380%到410%之間"
MONKEYSPEED_speedColour9_DESC			= "410%"
MONKEYSPEED_speedColour10_DESC			= "410%以上"
MONKEYSPEED_precision_DESC				= "小數點"

elseif (GetLocale() == "ruRU") then

MONKEYSPEED_GENERAL_OPTIONS				= "Общие Настройки:"
MONKEYSPEED_shown_DESC					= "Включить MonkeySpeed"
MONKEYSPEED_frameColour_DESC			= "Цвет рамки"
MONKEYSPEED_showBorder_DESC				= "Показать границу"
MONKEYSPEED_borderColour_DESC			= "Цвет границы"
MONKEYSPEED_frameLocked_DESC			= "Блокировка положения окна"
MONKEYSPEED_showBar_DESC				= "Цветная полоса дисплея"
MONKEYSPEED_showLDB_DESC				= "Обновить LDB плагин"
MONKEYSPEED_showLDB_inactive			= "неактивный"
MONKEYSPEED_showPercent_DESC			= "Показать процент текста"
MONKEYSPEED_autoCalibration_DESC		= "Оценить единицу скорости во время плавания и полета"
MONKEYSPEED_maximumSpeed_DESC			= "Показать максимальную скорость"
MONKEYSPEED_MISC_OPTIONS				= "Разные настройки:"
MONKEYSPEED_leftClickToggles_DESC		= "ЛКМ переключает окно MonkeySpeed"
MONKEYSPEED_shiftLeftClickLocks_DESC	= "Shift+ЛКМ блокирует/разблокирует окно"
MONKEYSPEED_rightClickOpensConfig_DESC	= "ПКМ открывает окно настроек"
MONKEYSPEED_speedColour1_DESC			= "Скорость при 0%"
MONKEYSPEED_speedColour2_DESC			= "Скорость при >0% и <100%"
MONKEYSPEED_speedColour3_DESC			= "Скорость при 100%"
MONKEYSPEED_speedColour4_DESC			= "Скорость при >100% и <200%"
MONKEYSPEED_speedColour5_DESC			= "Скорость при 200%"
MONKEYSPEED_speedColour6_DESC			= "Скорость при >200% и <380%"
MONKEYSPEED_speedColour7_DESC			= "Скорость при 380%"
MONKEYSPEED_speedColour8_DESC			= "Скорость при >380% и <410%"
MONKEYSPEED_speedColour9_DESC			= "Скорость при 410%"
MONKEYSPEED_speedColour10_DESC			= "Скорость при >410% до бесконечности"
MONKEYSPEED_precision_DESC				= "Десятичная точка"

elseif (GetLocale() == "zhCN") then

MONKEYSPEED_GENERAL_OPTIONS				= "一般选项"
MONKEYSPEED_shown_DESC					= "启用MonkeySpeed"
MONKEYSPEED_frameColour_DESC			= "窗口背景色"
MONKEYSPEED_showBorder_DESC				= "显示边框"
MONKEYSPEED_borderColour_DESC			= "边框颜色"
MONKEYSPEED_frameLocked_DESC			= "锁定位置"
MONKEYSPEED_showBar_DESC				= "以移动速度染色"
MONKEYSPEED_showLDB_DESC				= "信息条"
MONKEYSPEED_showLDB_inactive			= "开发中"
MONKEYSPEED_showPercent_DESC			= "显示百分比"
MONKEYSPEED_autoCalibration_DESC		= "估算游泳和飞行时的单位速度"
MONKEYSPEED_maximumSpeed_DESC			= "显示最快速度"
MONKEYSPEED_MISC_OPTIONS				= "细节选项："
MONKEYSPEED_leftClickToggles_DESC		= "左键点击拖动"
MONKEYSPEED_shiftLeftClickLocks_DESC	= "Shift+右键点击锁移动"
MONKEYSPEED_rightClickOpensConfig_DESC	= "右键点击开启配置选项"
MONKEYSPEED_speedColour1_DESC			= "0%"
MONKEYSPEED_speedColour2_DESC			= "0%到100%之间"
MONKEYSPEED_speedColour3_DESC			= "100%"
MONKEYSPEED_speedColour4_DESC			= "100%到200%"
MONKEYSPEED_speedColour5_DESC			= "200%"
MONKEYSPEED_speedColour6_DESC			= "200%到380%之间"
MONKEYSPEED_speedColour7_DESC			= "380%"
MONKEYSPEED_speedColour8_DESC			= "380%到410%之间"
MONKEYSPEED_speedColour9_DESC			= "410%"
MONKEYSPEED_speedColour10_DESC			= "410%以上"
MONKEYSPEED_precision_DESC				= "小数点"

end
