----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ptBR" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_ACTIVE"] = "Ativo"
L["BTWQUESTS_ALLIED_RACES"] = "Raças Aliadas"
L["BTWQUESTS_AVAILABLE"] = "Disponíveis"
L["BTWQUESTS_COMPLETED"] = "Concluído"
L["BTWQUESTS_COSMETIC"] = "Cosmético"
L["BTWQUESTS_EXPANSION_NAME0"] = "Clássico"
L["BTWQUESTS_FACTION"] = "Facção"
L["BTWQUESTS_IGNORED"] = "Ignorado"
L["BTWQUESTS_LEVEL"] = "Nível %d"
L["BTWQUESTS_MOUNT"] = "Montar"
L["BTWQUESTS_PET"] = "Ajudante"
L["BTWQUESTS_PROFESSIONS"] = "Profissões"
L["BTWQUESTS_PROFESSION_ALCHEMY"] = "Alquimia"
L["BTWQUESTS_PROFESSION_BLACKSMITHING"] = "Ferraria"
L["BTWQUESTS_PROFESSION_ENCHANTING"] = "Encantamento"
L["BTWQUESTS_PROFESSION_ENGINEERING"] = "Engenharia"
L["BTWQUESTS_PROFESSION_FIRST_AID"] = "Primeiros socorros"
L["BTWQUESTS_PROFESSION_FISHING"] = "Pesca"
L["BTWQUESTS_PROFESSION_HERBALISM"] = "Herborismo"
L["BTWQUESTS_PROFESSION_INSCRIPTION"] = "Escrivania"
L["BTWQUESTS_PROFESSION_JEWELCRAFTING"] = "Joalheria"
L["BTWQUESTS_PROFESSION_LEATHERWORKING"] = "Couraria"
L["BTWQUESTS_PROFESSION_MINING"] = "Mineração"
L["BTWQUESTS_PROFESSION_SKINNING"] = "Esfolamento"
L["BTWQUESTS_PROFESSION_TAILORING"] = "Alfaiataria"
L["BTWQUESTS_TOY"] = "Brinquedo"
L["BTWQUESTS_WORLD_QUESTS"] = "Missões Mundiais"
L["FACTION_REWARD"] = "Facção: %s"
L["OTHER"] = "Outro"
L["RANK"] = "%s Grau %d"
L["UNKNOWN"] = "Desconhecido"
