----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "esMX" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_ACTIVE"] = "Activo"
L["BTWQUESTS_ALLIED_RACES"] = "Razas aliadas"
L["BTWQUESTS_AVAILABLE"] = "Disponible"
L["BTWQUESTS_COMPLETED"] = "Completado"
L["BTWQUESTS_COSMETIC"] = "Cosmético"
L["BTWQUESTS_EXPANSION_NAME0"] = "World of Warcraft: Clásico"
L["BTWQUESTS_FACTION"] = "Facción"
L["BTWQUESTS_IGNORED"] = "Ignorado"
L["BTWQUESTS_LEVEL"] = "Nivel %d"
L["BTWQUESTS_MOUNT"] = "Montar"
L["BTWQUESTS_PET"] = "Mascota"
L["BTWQUESTS_PROFESSIONS"] = "Profesiones"
L["BTWQUESTS_PROFESSION_ALCHEMY"] = "Alquimia"
L["BTWQUESTS_PROFESSION_BLACKSMITHING"] = "Herrería"
L["BTWQUESTS_PROFESSION_ENCHANTING"] = "Encantamiento"
L["BTWQUESTS_PROFESSION_ENGINEERING"] = "Ingeniería"
L["BTWQUESTS_PROFESSION_FIRST_AID"] = "Primeros auxilios"
L["BTWQUESTS_PROFESSION_FISHING"] = "Pesca"
L["BTWQUESTS_PROFESSION_HERBALISM"] = "Herboristería"
L["BTWQUESTS_PROFESSION_INSCRIPTION"] = "Inscripción"
L["BTWQUESTS_PROFESSION_JEWELCRAFTING"] = "Joyería"
L["BTWQUESTS_PROFESSION_LEATHERWORKING"] = "Peletería"
L["BTWQUESTS_PROFESSION_MINING"] = "Minería"
L["BTWQUESTS_PROFESSION_SKINNING"] = "Desuello"
L["BTWQUESTS_PROFESSION_TAILORING"] = "Sastrería"
L["BTWQUESTS_TOY"] = "Juguete"
L["BTWQUESTS_WORLD_QUESTS"] = "Misiones de mundo"
L["FACTION_REWARD"] = "Facción: %s"
L["OTHER"] = "Otros"
L["RANK"] = "%s rango %d"
L["UNKNOWN"] = "Desconocido"
